[gateway] Fix data race in dialer tests (#3185)
Fix a race condition introduced in the cluster dialer tests that was
introduced in https://github.com/xataio/maki/pull/3179.

The RPC message structs can't be shared between parallel subtests;
replace them with functions that return new instances of the structs for
each subtest.

Reproducible before this fix:

```
$ go test ./services/gateway/session/ -race -count=5

==================
WARNING: DATA RACE
Read at 0x00c0003d2300 by goroutine 1047:
  reflect.Value.IsNil()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/value.go:1652 +0x2d4
  reflect.deepValueEqual.func1()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:53 +0x1b4
  reflect.deepValueEqual()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:58 +0x140
  reflect.deepValueEqual()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:130 +0x1928
  reflect.deepValueEqual()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:130 +0x1928
  reflect.deepValueEqual()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:127 +0x1360
  reflect.DeepEqual()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/reflect/deepequal.go:238 +0x1cc
  github.com/stretchr/testify/assert.ObjectsAreEqual()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/assert/assertions.go:70 +0x144
  github.com/stretchr/testify/mock.Arguments.Diff()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:1043 +0xd84
  github.com/stretchr/testify/mock.(*Mock).findExpectedCall()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:393 +0x10c
  github.com/stretchr/testify/mock.(*Mock).MethodCalled()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:501 +0x6c
  github.com/stretchr/testify/mock.(*Mock).Called()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:491 +0x12c
  xata/gen/protomocks.(*ClustersServiceClient).DescribePostgresCluster()
      /Users/andrew/git/xata/maki/gen/protomocks/ClustersServiceClient.go:258 +0x260
  xata/services/gateway/session.(*ClusterDialer).Dial()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer.go:148 +0x4c4
  xata/services/gateway/session.TestClusterDialer_ReactivationMetrics.func11()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer_test.go:1013 +0x3e4
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2193 +0x164
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x34

Previous write at 0x00c0003d2300 by goroutine 1036:
  ??()
      -:0 +0x106b0cd7c
  sync/atomic.StorePointer()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/runtime/atomic_pointer.go:92 +0x34
  xata/gen/proto/clusters/v1.(*DescribePostgresClusterRequest).ProtoReflect()
      /Users/andrew/git/xata/maki/gen/proto/clusters/v1/clusters.pb.go:438 +0x70
  google.golang.org/protobuf/encoding/prototext.MarshalOptions.Format()
      /Users/andrew/go/pkg/mod/google.golang.org/protobuf@v1.36.11/encoding/prototext/encode.go:93 +0x54
  google.golang.org/protobuf/internal/impl.Export.MessageStringOf()
      /Users/andrew/go/pkg/mod/google.golang.org/protobuf@v1.36.11/internal/impl/api_export.go:176 +0x68
  xata/gen/proto/clusters/v1.(*DescribePostgresClusterRequest).String()
      /Users/andrew/git/xata/maki/gen/proto/clusters/v1/clusters.pb.go:428 +0x30
  fmt.(*pp).handleMethods()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/fmt/print.go:666 +0x354
  fmt.(*pp).printArg()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/fmt/print.go:746 +0x8c0
  fmt.(*pp).doPrintf()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/fmt/print.go:1158 +0xc58
  fmt.Sprintf()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/fmt/print.go:231 +0x50
  github.com/stretchr/testify/mock.Arguments.Diff()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:987 +0x1e4
  github.com/stretchr/testify/mock.(*Mock).findExpectedCall()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:393 +0x10c
  github.com/stretchr/testify/mock.(*Mock).MethodCalled()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:501 +0x6c
  github.com/stretchr/testify/mock.(*Mock).Called()
      /Users/andrew/go/pkg/mod/github.com/stretchr/testify@v1.12.1/mock/mock.go:491 +0x12c
  xata/gen/protomocks.(*ClustersServiceClient).DescribePostgresCluster()
      /Users/andrew/git/xata/maki/gen/protomocks/ClustersServiceClient.go:258 +0x260
  xata/services/gateway/session.(*ClusterDialer).Dial()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer.go:148 +0x4c4
  xata/services/gateway/session.TestClusterDialer_ReactivationMetrics.func11()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer_test.go:1013 +0x3e4
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2193 +0x164
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x34

Goroutine 1047 (running) created at:
  testing.(*T).Run()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x7bc
  xata/services/gateway/session.TestClusterDialer_ReactivationMetrics()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer_test.go:995 +0x2d50
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2193 +0x164
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x34

Goroutine 1036 (running) created at:
  testing.(*T).Run()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x7bc
  xata/services/gateway/session.TestClusterDialer_ReactivationMetrics()
      /Users/andrew/git/xata/maki/services/gateway/session/cluster_dialer_test.go:995 +0x2d50
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2193 +0x164
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.27.1/libexec/src/testing/testing.go:2258 +0x34
==================
--- FAIL: TestClusterDialer_ReactivationMetrics (0.00s)
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_clusters_service_rpc_failed (0.00s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_canceled_during_update (0.00s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_deadline_exceeded_during_update (0.00s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/non-pooled (0.02s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/waited_-_wake_already_in_flight (0.02s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_unknown_instance_size (0.02s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_this_connection_triggered_the_wake (0.02s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_deadline_exceeded_during_describe (0.02s)
        testing.go:1865: race detected during execution of test
    --- FAIL: TestClusterDialer_ReactivationMetrics/reactivated_-_canceled_during_describe (0.02s)
        testing.go:1865: race detected during execution of test
--- FAIL: TestClusterDialer_Dial (0.00s)
    testing.go:1865: race detected during execution of test
FAIL
FAIL    xata/services/gateway/session   6.776s
FAIL
```